name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Running the webapp
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 35.239.103.30
        username: bitorsic
        passphrase: ${{ secrets.PASSPHRASE }}
        key: ${{ secrets.SSH_PRIV_KEY }}
        script: |
          cd express-hello-world
          git pull
          npm i
          pm2 restart index
          echo "Access the webapp at http://35.239.103.30"
